spring.application.name=PacePlanner
server.port=60123

spring.datasource.url=jdbc:mysql://localhost:3306/paceplanner
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ipgeolocation.api.key=0a7280294581441d99219dfc818e3d36